### ISSUE TITLE
New 1.8.0 Version crash on Forge 1.20.1 using Sinytra Connector v36 (1.7.4/prior version 100% OK)

### ISSUE THREAD

**Issue by hiimrickross** [mim1q/MineCells#113]
https://gist.github.com/hiimrickross/22705b854301cdf501f36bc30f4ab64f

lots of references to mine cells at the end

"Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method minecells$modifyIsCrossbowInGetArmPose(ZLnet/minecraft/client/player/AbstractClientPlayer;Lnet/minecraft/world/InteractionHand;)Z in minecells.mixins.json:client.PlayerEntityRendererMixin from mod minecells failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap minecells-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 52 more"

It will list an error with another mod that had no issue on 1.7.4, then say this caused by: minecells callback injection crossbow error.

I hope it can be resolved without much issue 🙏 I love mine cells mod
i am using an older version of connector but it worked just fine on 1.7.4 before, and newer version of connector crashes for me so i cant use it

**Comment by mim1q** [comment]
Same crash as https://github.com/mim1q/MineCells/issues/111, let's keep that one open

I have to wait for Connector devs to respond, it might be an incompatibility on their side
