### ISSUE TITLE
Crashing while launching Ramparts

### ISSUE THREAD

**Issue by 4seasonsandaporno** [mim1q/MineCells#127]
[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.crash.CrashException: Ticking memory connection
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:908) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Caused by: net.minecraft.util.InvalidIdentifierException: Non [a-z0-9/._-] character in path of location: minecraft:block/minecells:putrid_planks
	at net.minecraft.util.Identifier.validatePath(Identifier.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.util.Identifier.<init>(Identifier.java:47) ~[client-intermediary.jar:?]

[latest.log](https://github.com/user-attachments/files/16115016/latest.log)

**Comment by mim1q** [comment]
Try removing Signed Paintings and see if this issue still occurs, please 😁

**Comment by 4seasonsandaporno** [comment]
that fixed it thank you
