### ISSUE TITLE
Crash involving Valarian Conquest

### ISSUE THREAD

**Issue by otaldojonis** [mim1q/MineCells#138]
When I summon a specific valarian warrior via spawn egg, or when this same sentity is dismounted from thoe horse he ussualy spawns with, the game just crashes and I get an:

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "p_61926_" is null.

Suspected Mods: 
	Mine Cells (minecells), Version: 1.8.5
		Mixin class: com.github.mim1q.minecells.mixin.entity.MineCellsBorderEntityMixin
		Target: net.minecraft.world.entity.Entity
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.handler$eik000$minecells$cancelStartRiding(Entity.java:15610)

	Valarian Conquest (valarian_conquest), Version: 2.4
		at TRANSFORMER/valarian_conquest@2.4/net.mcreator.valarian_conquest.procedures.GuardValarianNoblemanProcedure.execute(GuardValarianNoblemanProcedure.java:16)

I don't know what any of these means but it only happens when minecells is present, so I assumed is not Valarian's fault
[crash-2024-10-14_21.49.06-client.txt](https://github.com/user-attachments/files/17370822/crash-2024-10-14_21.49.06-client.txt)

**Comment by mim1q** [comment]
Thanks for the report!
That mod seems to be made in MCreator, so I wouldn't be surprised if that was what caused the issue. I can't be sure since the code is now public.

This should also be fixable on my side though, I'll try to do that, reply here again and I'd appreciate a verification whether it works now
