### ISSUE TITLE
Crash because minecells:shockwave_flame_player

### ISSUE THREAD

**Issue by SpiritOTHawk** [mim1q/MineCells#140]
```
java.lang.IllegalArgumentException: Cannot get property class_2746{name=north, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecells:shockwave_flame_player}
	at knot//net.minecraft.class_2688.method_11654(class_2688.java:98)
	at knot//com.oscimate.firorize.test.TestModel$1.method_4707(TestModel.java:77)
	at knot//net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:59)
	at knot//net.minecraft.class_1087.emitBlockQuads(class_1087.java:1041)
	at knot//com.oscimate.firorize.test.TestModel.emitBlockQuads(TestModel.java:248)
	at knot//net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at knot//me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:52)
	at knot//net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at knot//net.minecraft.class_1095.emitBlockQuads(class_1095.java:601)
	at knot//net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at knot//me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
	at knot//net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at knot//me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:52)
	at knot//net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderContext.render(BlockRenderContext.java:79)
	at knot//org.embeddedt.embeddium.render.frapi.IndigoBlockRenderContext.renderEmbeddium(IndigoBlockRenderContext.java:156)
	at knot//me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(B
[crash-2024-10-30_17.20.34-client.txt](https://github.com/user-attachments/files/17574379/crash-2024-10-30_17.20.34-client.txt)
lockRenderer.java:114)
	at knot//me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:122)
	at knot//me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50)
	at knot//me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at knot//me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:221)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
[crash-2024-10-30_17.20.34-client.txt](https://github.com/user-attachments/files/17574380/crash-2024-10-30_17.20.34-client.txt)

**Comment by mim1q** [comment]
This may be a bug in the [Firorize](https://modrinth.com/mod/firorize) mod 🤔

**Comment by SpiritOTHawk** [comment]
Yes, it is
