### ISSUE TITLE
Crash when using Minecells in other dimensions

### ISSUE THREAD

**Issue by Kal1nc** [mim1q/MineCells#144]
Hello,

I'm currently having issues with spawning runes that are crashing my server when using a minecells portal in a dimension other than the overworld (similar to #71)

`java.lang.NullPointerException: Cannot read field "key" because "this.fromDimension" is null
	at knot//com.github.mim1q.minecells.world.state.MineCellsData$PlayerData$PortalData.writeNbt(MineCellsData.java:273)
	at knot//com.github.mim1q.minecells.world.state.MineCellsData$PlayerData.writeNbt(MineCellsData.java:206)
	at knot//com.github.mim1q.minecells.world.state.PlayerSpecificMineCellsData.lambda$toNbt$2(PlayerSpecificMineCellsData.java:39)
	at knot//com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292)
	at knot//com.github.mim1q.minecells.world.state.PlayerSpecificMineCellsData.toNbt(PlayerSpecificMineCellsData.java:39)
	at knot//com.github.mim1q.minecells.network.s2c.SyncMineCellsPlayerDataS2CPacket.<init>(SyncMineCellsPlayerDataS2CPacket.java:20)
	at knot//com.github.mim1q.minecells.network.s2c.SyncMineCellsPlayerDataS2CPacket.send(SyncMineCellsPlayerDataS2CPacket.java:36)
	at knot//com.github.mim1q.minecells.world.state.MineCellsData.syncCurrentPlayerData(MineCellsData.java:125)
	at knot//com.github.mim1q.minecells.data.spawner_runes.SpawnerRuneController.tick(SpawnerRuneController.java:48)
	at knot//com.github.mim1q.minecells.block.blockentity.SpawnerRuneBlockEntity.tick(SpawnerRuneBlockEntity.java:20)
	at knot//com.github.mim1q.minecells.block.SpawnerRuneBlock.lambda$getTicker$0(SpawnerRuneBlock.java:62)
	at knot//net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(class_2818.java)
	at knot//com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:210)
	at knot//net.minecraft.class_2818$class_5563.wrapOperation$gaj000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(class_2818.java:1287)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:470)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:390)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:283)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)
`

In this case I used multiworld to create another overworld dimension

**Comment by RealStraith** [comment]
why did you close it as completed if its still there
