### ISSUE TITLE
Crash with RPG difficulty mod

### ISSUE THREAD

**Issue by slammaja** [mim1q/MineCells#35]
Hi,

after updating to version 1.4.1 there seems to be some conflict with RPG difficulty mod:

java.lang.NoSuchMethodError: 'void net.rpgdifficulty.api.MobStrengthener.changeAttributes(net.minecraft.class_1308, net.minecraft.class_1937)'
     at com.github.mim1q.minecells.block.blockentity.spawnerrune.SpawnerRuneBlockEntity.spawnEntity(SpawnerRuneBlockEntity.java:86)
     at com.github.mim1q.minecells.block.blockentity.spawnerrune.SpawnerRuneBlockEntity.spawnEntities(SpawnerRuneBlockEntity.java:77)
     at com.github.mim1q.minecells.block.blockentity.spawnerrune.SpawnerRuneBlockEntity.tick(SpawnerRuneBlockEntity.java:50)
     at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
     at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
     at net.minecraft.class_1937.redirect$ekk000$observable$redirectTick(class_1937.java:8567)
     at net.minecraft.class_1937.method_18471(class_1937.java:456)
     at net.minecraft.class_3218.method_18765(class_3218.java:376)
     at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
     at net.minecraft.class_3176.method_3813(class_3176.java:289)
     at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
     at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
     at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
     at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mim1q** [comment]
Hey, are you using the latest RPGDifficulty version?

**Comment by slammaja** [comment]
Yes, I am using latest version (1.3.7). I tried downgrading to version 1.3.5 I used prior updating. Both resulting in crash as soon as mob spawned im minecells dimension.

**Comment by mim1q** [comment]
I see. Well, this compatibility has been causing quite a bit of issues, I'll probably remove it soon

**Comment by mim1q** [comment]
Most probably fixed with [this version](https://modrinth.com/mod/minecells/version/h24wvKrs)!
