### ISSUE TITLE
Lithium and Mine Cells incompatibility

### ISSUE THREAD

**Issue by tealander** [mim1q/MineCells#48]
![image](https://github.com/mim1q/MineCells/assets/132600738/31d8083f-80b8-4b17-8108-24274ef2c3cc)

This happens when you're trying to run your game with Lithium enabled.

Crash Log:
[Mine Cells](#) is conflicting with [Lithium](https://github.com/CaffeineMC/lithium-fabric).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("STORE" ordinal=-1 index=-1) on net/minecraft/class_1297::minecells$modifyWorldBorderWhenAdjustingMovement with priority 1000 cannot inject into net/minecraft/class_1297::method_20736(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;Lnet/minecraft/class_238;Lnet/minecraft/class_1937;Ljava/util/List;)Lnet/minecraft/class_243; merged by me.jellysquid.mods.lithium.mixin.entity.collisions.movement.EntityMixin with priority 1000 [ -> localvar$inj000$minecells$modifyWorldBorderWhenAdjustingMovement(Lnet/minecraft/class_2784;Lnet/minecraft/class_1297;Lnet/minecraft/class_243;Lnet/minecraft/class_238;Lnet/minecraft/class_1937;Ljava/util/List;)Lnet/minecraft/class_2784; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3543)
	at java.base/java.lang.Class.getMethod0(Class.java:3529)
	at java.base/java.lang.Class.getMethod(Class.java:2225)
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3828)
	at java.base/java.lang.Class.getEnumConstants(Class.java:3812)
	at dev.quantumfusion.hyphen.codegen.def.EnumDef.scan(EnumDef.java:39)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:101)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:101)
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112)
	at dev.quantumfusion.hyphen.codegen.def.IndexedDef.<init>(IndexedDef.java:27)
	at dev.quantumfusion.hyphen.codegen.def.ListDef.<init>(ListDef.java:16)
	at dev.quantumfusion.hyphen.codegen.def.ListDef.<init>(ListDef.java:25)
	at dev.quantumfusion.hyphen.SerializerHandler.lambda$static$1(SerializerHandler.java:35)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDefNew(SerializerHandler.java:125)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:109)
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112)
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112)
	at dev.quantumfusion.hyphen.codegen.def.SubclassDef.lambda$scan$1(SubclassDef.java:29)
	at dev.quantumfusion.hyphen.util.ArrayUtil.map(ArrayUtil.java:74)
	at dev.quantumfusion.hyphen.codegen.def.SubclassDef.scan(SubclassDef.java:29)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:101)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:101)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:101)
	at dev.quantumfusion.hyphen.codegen.def.IndexedDef.<init>(IndexedDef.java:27)
	at dev.quantumfusion.hyphen.codegen.def.ArrayDef.<init>(ArrayDef.java:16)
	at dev.quantumfusion.hyphen.codegen.def.ArrayDef.<init>(ArrayDef.java:22)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDefNewMethod(SerializerHandler.java:138)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDefNew(SerializerHandler.java:128)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:109)
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112)
	at dev.quantumfusion.hyphen.codegen.def.SubclassDef.lambda$scan$1(SubclassDef.java:29)
	at dev.quantumfusion.hyphen.util.ArrayUtil.map(ArrayUtil.java:74)
	at dev.quantumfusion.hyphen.codegen.def.SubclassDef.scan(SubclassDef.java:29)
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112)
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43)
	at dev.quantumfusion.hyphen.SerializerHandler.scan(SerializerHandler.java:162)
	at dev.quantumfusion.hyphen.SerializerHandler.build(SerializerHandler.java:169)
	at dev.quantumfusion.hyphen.SerializerFactory.build(SerializerFactory.java:181)
	at dev.quantumfusion.dashloader.io.serializer.DashSerializer.create(DashSerializer.java:73)
	at dev.quantumfusion.dashloader.io.IOHandler.addSerializer(IOHandler.java:34)
	at dev.quantumfusion.dashloader.DashLoader.initialize(DashLoader.java:102)
	at net.minecraft.client.main.Main.handler$fal000$dashloader$main(Main.java:520)
	at net.minecraft.client.main.Main.main(Main.java)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## Mod list
```
- additionaladditions 5.1.0
- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
- advancementframes 1.19.2-2.0.0
- advancementinfo 1.19.1-fabric0.58.5-1.3.1
- advancementplaques 1.4.6
- adventurez 1.4.18
- angling 1.0.1
- animatica 0.5+1.19
- another_furniture 2.1.2-1.19.2
- antighost 1.19.1-fabric0.58.5-1.1.5
- appleskin 2.4.1+mc1.19
- architectury 6.5.85
- areas 5.0
- attributefix 17.2.7
- auditory 0.0.4-1.19.x
- bclib 2.1.7
- beachparty 1.0.6
- beautify 1.1.1+fabric-1.19.2
- bedspreads 6.0.0+1.19.2
- beekeeperhut 1.2.0
- betteradvancements 0.3.0.148
- betterbeds 1.2.0
- betterbiomeblend 1.19-1.3.6-fabric
- betterdeserttemples 1.19.2-Fabric-2.2.2
- betterdungeons 1.19.2-Fabric-3.2.1
- betterend 2.1.6
- betterf3 4.0.0
- betterfortresses 1.19.2-Fabric-1.0.6
- betterfpsdist 1.19-2.4
- bettermineshafts 1.19.2-Fabric-3.2.0
- bettermounthud 1.2.0
- betternether 7.1.4
- betteroceanmonuments 1.19.2-Fabric-2.1.0
- betterpingdisplay 1.1.1
- betterstats 2.9.3+1.19.2
- betterstrongholds 1.19.2-Fabric-3.2.0
- betterwitchhuts 1.19.2-Fabric-2.1.0
- blossom 1.0.7
- blue_endless_jankson 1.2.2 via frozenlib
- blur 2.6.0
- boatiview 0.0.4
- bobby 4.0.1
- bookshelf 16.3.20
- bountiful 3.0.0
- byg 2.0.1.4
- c2me 0.2.0+alpha.9.10
- c2me-base 0.2.0+alpha.9.10 via c2me
- c2me-client-uncapvd 0.2.0+alpha.9.10 via c2me
- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.9.10 via c2me
- c2me-fixes-general-threading-issues 0.2.0+alpha.9.10 via c2me
- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.9.10 via c2me
- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.9.10 via c2me
- c2me-notickvd 0.2.0+alpha.9.10 via c2me
- c2me-opts-allocs 0.2.0+alpha.9.10 via c2me
- c2me-opts-chunk-access 0.2.0+alpha.9.10 via c2me
- c2me-opts-chunkio 0.2.0+alpha.9.10 via c2me
- c2me-opts-math 0.2.0+alpha.9.10 via c2me
- c2me-opts-scheduling 0.2.0+alpha.9.10 via c2me
- c2me-opts-worldgen-general 0.2.0+alpha.9.10 via c2me
- c2me-opts-worldgen-vanilla 0.2.0+alpha.9.10 via c2me
- c2me-rewrites-chunkio 0.2.0+alpha.9.10 via c2me
- c2me-server-utils 0.2.0+alpha.9.10 via c2me
- c2me-threading-chunkio 0.2.0+alpha.9.10 via c2me
- c2me-threading-lighting 0.2.0+alpha.9.10 via c2me
- c2me-threading-scheduling 0.2.0+alpha.9.10 via c2me
- c2me-threading-worldgen 0.2.0+alpha.9.10 via c2me
- caffeineconfig 1.0.0+1.17 via sodium-extra
- cardinal-components-base 5.0.2 via beautify
- cardinal-components-block 5.0.2 via polymorph
- cardinal-components-chunk 5.0.2 via puzzleslib
- cardinal-components-entity 5.0.2 via beautify
- cardinal-components-item 5.0.2 via polymorph
- cardinal-components-world 5.0.2 via beautify
- carpet 1.4.84
- carpet-extra 1.4.84
- carpet-fixes 1.19-1.12.2
- cavedust 1.2.0
- charm 4.4.4
- charmonium 4.2.1
- chat_heads 0.10.18
- chatpatches 192.2.1
- chefsdelight 1.0.3-fabric-1.19.2
- cherishedworlds 6.0.5+1.19.4
- chipped 2.1.5
- choicetheorems_overhauledvillagefriendsandfoesaddon_mr 1.1
- chunksending 1.19-2.5
- chunksfadein 3.0.11-1.19
- cicada 0.1.2 via do_a_barrel_roll
- citresewn 1.1.2+1.19.2
- citresewn-defaults 1.1.2+1.19.2 via citresewn
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.3.103
- coat 1.0.0-beta.18+mc22w17a via wandering_collector
- coffee_delight 1.3
- collective 6.65
- com_electronwill_night-config_core 3.6.6 via corgilib
- com_electronwill_night-config_toml 3.6.6 via corgilib
- com_eliotlash_mclib_mclib 20 via geckolib3
- com_github_llamalad7_mixinextras 0.2.0-beta.8 via friendsandfoes
- com_github_luben_zstd-jni 1.5.2-2 via dashloader
- com_google_code_findbugs_jsr305 3.0.2 via create
- com_ibm_async_asyncutil 0.1.0 via c2me
- com_moandjiezana_toml_toml4j 0.7.2 via charm
- com_sksamuel_scrimage_scrimage-core 4.0.31 via mru
- com_typesafe_config 1.4.2 via bobby
- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
- conditional-mixin 0.3.2 via fastload
- connectedglass 1.1.7
- connectiblechains 2.1.4+1.19.2
- continuity 2.0.2+1.19
- convenientdecor 0.1.0
- corgilib 1.0.0.34
- cosmetic-armor 1.4.2
- craftify 1.11.0
- craftpresence 2.1.2
- crafttweaker 10.1.47
- crawl 0.11.1
- create 0.5.1-b-build.1089+mc1.19.2
- create_so 1.3.3+fabric-1.19.2
- creeperoverhaul 2.0.9
- crittersandcompanions 1.19.2-2.0.1
- crowdin-translate 1.4+1.19 via antighost
- ctm 1.0.1+1.19
- ctov 3.2.5
- ctov_beautifyaddon_mr 1.0
- ctov_bountifulcompat_mr 1.0
- ctov_farmersdelightcompat_mr 1.2
- culturaldelights 0.14.9+1.19.2
- dangerousstonecutter 1.7.2
- dark-loading-screen 1.6.12
- dashloader 4.1.3+1.19
- dawn 3.5.0
- debugify 2.8.0
- dev_quantumfusion_hyphen 0.2.2 via dashloader
- dev_quantumfusion_taski 1.1.0 via dashloader
- direbats 3.1.0+1.19.2
- disable_custom_worlds_advice 3.0 via nethersdelight
- dismountentity 3.0
- do_a_barrel_roll 2.6.2+1.19.2
- doapi 1.0.4 via beachparty
- dripstone_fluid_lib 2.0.1 via milk
- droplight 1.0.5
- dynamicfps 2.2.0
- dynview 1.19-2.4
- easyanvils 4.0.11
- easymagic 4.3.3
- easyshulkerboxes 4.4.1
- eatinganimationid 1.9.1
- eldritch_mobs 1.13.1
- elementa 590 via craftify
- emi 1.0.11+1.19.2+fabric
- emi_loot 0.6.4+1.19
- emicompat 2.0.3
- emiffect 0.1.5+mc1.19.2
- emitrades 1.0.2+mc1.19.2
- enchanted-vertical-slabs 1.8
- enchdesc 13.0.14
- enchlevel-langpatch 2.1.2
- endrem 5.2.0
- enhanced_attack_indicator 1.0.4+1.19
- enhancedblockentities 0.7.2+1.19.2
- enhancedcelestials 2.1.0.6
- entity_texture_features 4.4.4
- entitycollisionfpsfix 2.0.0.0
- entityculling 1.6.1-mc1.19.2
- equipmentcompare 1.3.1
- exordium 1.0.2-mc1.19.2
- expandeddelight 0.2.5
- explorify-fabric 1.19-1.3.0
- extrasounds 2.3.1+1.19.2-1.19.1
- fabric-api 0.76.0+1.19.2
- fabric-api-base 0.4.15+8f4e8eb390 via fabric-api
- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.1.1+16f1e31390 via fabric-api
- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90 via fabric-api
- fabric-client-tags-api-v1 1.0.5+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
- fabric-command-api-v2 2.2.1+413cbbc790 via fabric-api
- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
- fabric-containers-v0 0.1.41+df3654b390 via fabric-api
- fabric-content-registries-v0 3.5.2+7c6cd14d90 via fabric-api
- fabric-convention-tags-v1 1.3.0+4bc6e26290 via fabric-api
- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.3.8+413cbbc790 via fabric-api
- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
- fabric-events-lifecycle-v0 0.2.36+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- fabric-item-api-v1 1.6.6+b7d1888890 via fabric-api
- fabric-item-groups-v0 0.3.39+9244241690 via fabric-api
- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
- fabric-language-kotlin 1.10.8+kotlin.1.9.0
- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via fabric-api
- fabric-loot-api-v2 1.1.13+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.16+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.24+33fbc73890 via fabric-api
- fabric-models-v0 0.3.21+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.11+10eb22f490 via fabric-api
- fabric-networking-v0 0.3.28+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.2.2+d8ef690890 via fabric-api
- fabric-particles-v1 1.0.14+4d0d570390 via fabric-api
- fabric-permissions-api-v0 0.2-SNAPSHOT via servercore
- fabric-recipe-api-v1 1.0.1+413cbbc790 via fabric-api
- fabric-registry-sync-v0 0.9.32+9244241690 via fabric-api
- fabric-renderer-api-v1 1.2.1+1adbf27790 via fabric-api
- fabric-renderer-indigo 0.8.0+1adbf27790 via fabric-api
- fabric-renderer-registries-v1 3.2.24+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 via fabric-api
- fabric-rendering-fluids-v1 3.0.11+4d0d570390 via fabric-api
- fabric-rendering-v0 1.1.27+df3654b390 via fabric-api
- fabric-rendering-v1 1.12.1+d8ef690890 via fabric-api
- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.8.4+edbdcddb90 via craftpresence
- fabric-screen-api-v1 1.0.32+4d0d570390 via fabric-api
- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.24+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- fabricloader 0.14.21
- fabricskyboxes 0.7.2+mc1.19.2
- fallingleaves 1.13.0+1.19.2
- fallingtree 3.10.0
- farmersdelight 1.19.2-1.3.10
- farsighted-mobs 1.1-1.18-1.19
- faster_entity_animations 1.5.7
- fastload 3.4.0
- fastload-119-0-1-2-compat 3.4.0 via fastload
- fastload-1193-compat 3.4.0 via fastload
- fastload-1194-compat 3.4.0 via fastload
- fastload_fapi_forward 1.0.2 via fastload
- ferritecore 5.0.3
- fiber 0.23.0-2 via patchouli
- flywheel 0.6.8.a-5 via create
- forge_tags 3.0 via create
- forgeconfigapiport 4.2.11
- friendsandfoes 1.8.5
- frostiful 0.5.5
- frozenlib 1.2.6-Fabric+1.19.2 via wilderwild
- fuelinfo 1.0.1+1.19
- galosphere 1.19.2-1.3.0
- geckolib3 3.1.40
- geodes 1.7+1.19
- globaldataandresourcepacks 1.14.5_fabric
- goblintraders 1.5.2
- harvest_scythes 2.5.4+mc1.19.2
- healingcampfire 5.1
- highlighter 1.1.4
- huskspawn 3.3
- iceberg 1.0.46
- illagerexp 1.0.0
- illagerslovearmor 1.0.2+1.19
- immediatelyfast 1.1.12
- immersive_weathering 1.19.2-1.2.9
- impactfulweather 4.0.5
- incendium 5.1.6
- indium 1.0.9+mc1.19.2
- ingredient-extension-api 3.0.6
- io_leangen_geantyref_geantyref 1.3.13 via bobby
- itemswapper 0.4.0-mc1.19.2
- jankson 4.1.1+j1.2.1 via libgui
- java 17
- jeed 1.19.2-2.1.4
- jei 11.6.0.1016
- jeitweaker 4.0.12
- jeresources 1.2.2.200
- justenoughprofessions 2.0.2
- kambrik 4.0-1.19.2
- kirin 1.11.1 via presencefootsteps
- krypton 0.2.1
- lambdabettergrass 1.3.0+1.19
- lambdynlights 2.2.0+1.19.2
- langfiles-plus 1.0.0 via cicada
- languagereload 1.5.8+1.19.2
- lazydfu 0.1.3
- leavesbegone 4.0.1
- legendarytooltips 1.3.3
- letmedespawn fabric-1.0.2
- libgui 6.0.0-beta.5+1.19-pre1 via additionaladditions
- libninepatch 1.1.0 via libgui
- lithium 0.11.1
- logprot 1.19-1.9
- lootgoblins 1.0.8
- lowfire 1.19-3.0.0
- make_bubbles_pop 0.1.0-fabric
- mavapi 1.1.1
- mavm 1.2.4
- mcwifipnp 1.6.2
- me_lucko_spark-api 0.1-SNAPSHOT via servercore
- measurements 1.3.1
- memoryleakfix 1.1.1
- merchantmarkers 1.3.1
- midnightlib 1.0.0
- milk 1.0.51 via create
- mindfuldarkness 4.0.9
- minecells 1.5.1
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- mixintrace 1.1.1+1.17
- mm 2.3 via crawl
- modelfix 1.8
- modmenu 4.2.0-beta.2
- monsters_in_the_closet 1.0.3+1.19
- moonlight 1.19.2-2.2.43
- more_mobs_mr 1.4
- morebannerfeatures 1.1.3
- moreculling 1.19.1-0.17.0
- moremobvariants 1.0.1
- mousetweaks 2.22
- mru 0.1.5+1.19.2
- naturalist 3.0.2
- naturescompass 1.19.2-2.1.0-fabric
- nbtcrafting 2.2.3+mc1.19 via wilderwild
- net_lenni0451_reflect 1.1.0 via immediatelyfast
- net_objecthunter_exp4j 0.4.8 via c2me
- nethersdelight 1.0.1
- no-telemetry 1.7.0
- nochatreports 1.19.2-v1.13.12
- notenoughanimations 1.6.2
- nounusedchunks 2.0+1.19.2
- nullscape 1.2.1
- omega-config 1.2.3-1.18.1 via minecells
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_javassist_javassist 3.29.0-GA via crafttweaker
- org_jetbrains_kotlin_kotlin-reflect 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_reflections_reflections 0.10.2 via betterdeserttemples
- org_spongepowered_configurate-core 4.1.2 via bobby
- org_spongepowered_configurate-hocon 4.1.2 via bobby
- org_threadly_threadly 7.0 via c2me
- our_villager_discounts 1.19.2+build.1
- owo 0.9.3+1.19
- packet_tweaker 0.3.0+1.18.2 via server_translations_api
- patchouli 1.19.2-77-FABRIC
- philipsruins 1.19.2
- pickupnotifier 4.2.4
- pineapple_delight 1.0.6
- placeholder-api 2.0.0-pre.1+1.19.2 via servercore
- player-data-api 0.2.2+1.19.2 via styledchat
- polymer 0.2.28+1.19.2 via polymer-all
- polymer-all 0.2.28+1.19.2
- polymer-blocks-ext 0.1.0-alpha.9+1.19.2 via eldritch_mobs
- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
- polymorph 0.46.4+1.19.2
- porting_lib_accessors 2.1.1038+1.19.2 via create
- porting_lib_attributes 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_base 2.1.1038+1.19.2 via create
- porting_lib_common 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_constants 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_entity 2.1.1038+1.19.2 via create
- porting_lib_extensions 2.1.1038+1.19.2 via create
- porting_lib_fake_players 2.1.1038+1.19.2 via create
- porting_lib_lazy_registration 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_loot 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_model_generators 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_model_loader 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_models 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_networking 2.1.1038+1.19.2 via create
- porting_lib_obj_loader 2.1.1038+1.19.2 via create
- porting_lib_transfer 2.1.1038+1.19.2 via create
- predicate-api 0.1.0+1.19.2 via styledchat
- presencefootsteps 1.6.4
- pride 1.1.2+1.19 via lambdynlights
- prism 1.0.3
- puzzleslib 4.4.3
- pyrotastic 1.19+2.0.3
- railways 1.4.3+fabric-mc1.19.2
- raknetify 0.1.0+alpha.5.88
- randommobeffects 3.1
- reach-entity-attributes 2.3.0 via create
- reacharound 1.1.2
- reeses-sodium-options 1.4.9+mc1.19.2-build.67
- registrate-fabric 1.1.58-MC1.19.2 via create
- repurposed_structures 6.3.24+1.19.2
- resourcefulconfig 1.0.20
- resourcefullib 1.1.24
- rottencreatures 1.0.1
- rpgdifficulty 1.3.12
- satin 1.8.0 via blur
- serialization_hooks 0.3.26 via porting_lib_base
- server_translations_api 1.4.18+1.19.2 via eldritch_mobs
- servercore 1.3.3-1.19.2
- skinlayers 1.5.2-mc1.19.1
- skylorlib 1.5.1
- sleepwarp 2.0.0+1.19.2
- sliceanddice 2.2.1
- slotlock 1.1.1-BETA+1.19
- smarterfarmers 1.19.2-1.7.1
- smoothboot 1.19-1.7.1
- smoothchunk 1.19.2-3.0
- smoothswapping 0.9.2
- sodium 0.4.4+build.18
- sodium-extra 0.4.16+mc1.19.2-build.90
- sound_physics_remastered 1.19.2-1.0.18
- soundcategories 1.2.4+1.19 via extrasounds
- spectrelib 0.12.5+1.19.2 via polymorph
- spruceui 4.1.0+1.19.2 via lambdynlights
- spyglass-improvements 1.4+mc1.19+fabric
- starlight 1.1.1+fabric.ae22326
- stendhal 1.3.4-1.19
- strayspawn 3.3
- structory 1.3.1a
- structurized-reborn 1.19-01 via chefsdelight
- styledchat 2.0.3+1.19.2
- styledplayerlist 2.2.2+1.19.1
- supermartijn642corelib 1.1.11
- supplementaries 1.19.2-2.3.20
- tcdcommons 2.9.1+1.19.2 via betterstats
- team_reborn_energy 2.0.0-beta1 via emicompat
- terrablender 2.0.1.166
- terraform-wood-api-v1 4.2.0 via culturaldelights
- thermoo 1.4
- thonkutil 2.15.4+1.19
- thonkutil-base 1.13.2+4a8c408a57 via thonkutil
- thonkutil-capes-v1 1.4.2+3eb2749857 via thonkutil
- thonkutil-coords-v1 1.1.2+8ff533c957 via thonkutil
- thonkutil-customization-v1 1.1.2+8ff533c957 via thonkutil
- thonkutil-legacy 1.1.2+5d4263f557 via thonkutil
- thonkutil-modchecker-v1 1.1.3+bd4b387957 via thonkutil
- thonkutil-potions-v0 1.5.2+8ff533c957 via thonkutil
- thonkutil-titlescreen-v1 1.2.2+8ff533c957 via thonkutil
- thonkutil-trades-v1 1.2.2+8ff533c957 via thonkutil
- tipthescales 6.0.10
- tooltipfix 1.1.1-1.19
- trade_cycling 1.19.2-1.0.5
- tradingpost 4.2.0
- travelerstitles 1.19.2-Fabric-3.1.0
- trinkets 3.4.2
- tweed4_annotated 1.3.1+mc22w17a via wandering_collector
- tweed4_base 1.6.0+mc22w17a via wandering_collector
- tweed4_data 1.2.1+mc22w17a via wandering_collector
- tweed4_data_hjson 1.1.1+mc22w17a via wandering_collector
- tweed4_tailor_coat 1.1.3+mc22w17a via wandering_collector
- tweed4_tailor_screen 1.1.1+mc22w17a via wandering_collector
- twigs 3.0.0
- universal_ores 1.4.2
- universalcraft 269 via craftify
- v_slab_compat 1.19.2-1.4
- vigilance 284 via craftify
- vinery 1.3.1
- visuality 0.5.6
- visualworkbench 4.2.4
- vmp 0.2.0+beta.7.30
- vt_downloader 2.0.0
- wabi_sabi_structures 1.1.2
- wandering_collector 1.1.3+mc1.19
- waterdripsound 1.19-0.3.0
- wetlands 1.1.0
- wilderwild 2.0.6-Fabric+1.19.2
- windchimes 1.2.1
- wwoo 3.1.9.1
- xxlpackets 1.0.4-1.19.x-1.19.2
- yet-another-config-lib 2.2.0-for-1.19.2
- yosbr 0.1.2
- yungsapi 1.19.2-Fabric-3.8.9
- yungsextras 1.19.2-Fabric-3.1.0
```

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.21

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

**Comment by mim1q** [comment]
Fixed with 99ce325
Available to download as version 1.5.2 on Modrinth. CurseForge is under review 😁
