### ISSUE TITLE
Odd server crash due to minecells?

### ISSUE THREAD

**Issue by Micaxs** [mim1q/MineCells#71]
Had a odd crash on a fabric server with minecells, not entirely sure what the issue is but here's the error from crash-report.

`Time: 2023-11-23 22:12:20
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot read field "key" because "id" is null
	at com.github.mim1q.minecells.world.state.MineCellsData$PlayerData.writeNbt(MineCellsData.java:200)
	at com.github.mim1q.minecells.world.state.MineCellsData$RunData.writeNbt(MineCellsData.java:157)
	at com.github.mim1q.minecells.world.state.MineCellsData.method_75(MineCellsData.java:67)
	at net.minecraft.class_18.method_17919(class_18.java:36)
	at net.minecraft.class_26.method_32384(class_26.java:123)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at net.minecraft.class_26.method_125(class_26.java:121)
	at net.minecraft.class_3218.method_14188(class_3218.java:775)
	at net.minecraft.class_3218.method_14176(class_3218.java:757)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:526)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:550)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:844)
	at net.minecraft.server.MinecraftServer.handler$cfj000$carpet$modifiedRunLoop(MinecraftServer.java:7385)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)`

MC Version: 1.19.2
MineCells Mod version: 1.5.3
Fabric Loader: 0.14.24

**Comment by M1hono** [comment]
I have the same issue.

**Comment by Micaxs** [comment]
> I have the same issue.

Might just be an issue that the mod not supporting multiple worlds. Removing portals in another dimension besides the overworld seems to have fixed it so far for me. As the portals in another dimension spawn at the exact same coords as the one's in the overworld, and thus causing that crash.

**Comment by mim1q** [comment]
Sorry for not responding - so this happens when you place the Prisoners' Quarters Doorway in a dimension other than the overworld, right?

**Comment by M1hono** [comment]
> 抱歉沒有回覆 - 所以當你將囚犯宿舍門口放置在主世界以外的維度時就會發生這種情況，對嗎？

Yes

**Comment by Micaxs** [comment]
> Sorry for not responding - so this happens when you place the Prisoners' Quarters Doorway in a dimension other than the overworld, right?

Yes, did create a seperate dimension with default overworld generation (it generates the protal in that dimension as well). Seems to happen when players enter the portal inside that dimension. 
My current fix was to regenerate the dimension without the mod loaded so it doesn't generate the portals there, kinda a hotfix but would be nice to support multiple dimension portals as well but if thats too much work/effort, don't worry about it as this hotfix currently works fine.

**Comment by M1hono** [comment]
I thought It would be better if the configuration can contorl the spawn dimension of overworld portals.

**Comment by Viperpng** [comment]
Issue is still present in May 2024. Entered the Promenade of The Condemned portal and it crashed my server. Crashes the server every time i attempt to rejoin as well.

**Comment by mim1q** [comment]
> Issue is still present in May 2024. Entered the Promenade of The Condemned portal and it crashed my server. Crashes the server every time i attempt to rejoin as well.

Can you please send the crash log?

**Comment by mim1q** [comment]
> Issue is still present in May 2024. Entered the Promenade of The Condemned portal and it crashed my server. Crashes the server every time i attempt to rejoin as well.

Can you please send the crash log?
