### ISSUE TITLE
Game won't boot up

### ISSUE THREAD

**Issue by Igneo220** [mim1q/MineCells#9]
maybe issues with some mods, idk. I just have a crash log here:

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.fabricmc.fabric.api.object.builder.v1.villager.VillagerProfessionBuilder.build(VillagerProfessionBuilder.java:183)
	at com.miskatonicmysteries.common.registry.MMEntities.<clinit>(MMEntities.java:116)
	at com.miskatonicmysteries.common.registry.MMWorld.creatHasturBiome(MMWorld.java:111)
	at com.miskatonicmysteries.common.registry.MMWorld.<clinit>(MMWorld.java:97)
	at net.minecraft.class_5468.handler$fhe000$inject(class_5468.java:518)
	at net.minecraft.class_5468.method_30600(class_5468.java)
	at net.minecraft.class_5468.<clinit>(class_5468.java:14)
	at net.minecraft.class_3791.<clinit>(class_3791.java:11)
	at net.minecraft.class_5470.<clinit>(class_5470.java:72)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1805 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3852.<clinit>(class_3852.java:36)
	... 20 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 25 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector changeEffects(Lnet/minecraft/class_1309;)Z in takesapillage.mixins.json:MilkBucketMixin from mod takesapillage failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap takesapillage-1.19-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more

Yes i am using alot of other mods but the issue is not present when i remove this mod

It looks like an incompatibility with miskatonic mysteries. I'll go post the same issue on their end to see if it can get me a solution

**Comment by mim1q** [comment]
Hello! This is probably an issue with It Takes a Pillage. Can you please verify if it still crashes without that mod? If so, a bugfix is already implemented and will be available in the next release.

**Comment by mim1q** [comment]
No longer crashes as of 1.2.2. Closing!
